# title: plot universal PBM data
# author: Bin He
# date: 2024-03-21
# output: html_notebook

# goal: plot the uPBM data generated by Yuning Zhang at Raluca Gordân's lab at Duke.

require(tidyverse)
require(cowplot)
require(ggpubr)

# Date wrangling
header <- c("7mer", "7mer_comp", "E", "Median", "Z")
files.Sc <- dir("../output", pattern = "scPho4_488_550_5_7mers_1", full.names = TRUE)
files.Cg <- dir("../output", pattern = "cgPho4_488_550_5_7mers_1", full.names = TRUE)
rawSc = map_dfr(files.Sc, \(f) read_tsv(f, skip = 1, col_names = header))
rawCg = map_dfr(files.Cg, \(f) read_tsv(f, skip = 1, col_names = header))
dat <- inner_join(rawSc, rawCg, by = c("7mer", "7mer_comp"),
                 suffix = c(".Sc", ".Cg")) %>% 
  mutate(
    group = ifelse(E.Sc > 0.35 | E.Cg > 0.35, "bound", "unbound"),
    Ebox = grepl("CACGTG", `7mer`)
  )

# Calculating correlation coefficient
corr <- with(dat, cor(E.Sc, E.Cg, method = "spearman"))

# Plot
p <- dat %>% 
  ggplot(aes(x = E.Sc, y = E.Cg)) +
  #geom_point(data = filter(dat, group == "bound"), size = 0.3) +
  geom_hex(color = NA, bins = 128) +
  geom_point(data = filter(dat, Ebox), color = "red", size = 0.8) +
  geom_vline(xintercept = 0.35, color = "red", linetype = 3) +
  geom_hline(yintercept = 0.35, color = "red", linetype = 3) +
  scale_x_continuous(breaks = c(-0.5, 0, 0.35, 0.5)) +
  scale_y_continuous(breaks = c(-0.5, 0, 0.35, 0.5)) +
  xlab("ScPho4 E-score") +
  ylab("CgPho4 E-score") +
  theme_cowplot() + panel_border(color = "gray30", size = 1.5) +
  theme(
    axis.line = element_blank(),
    #axis.text = element_text(size = rel(1)),
    legend.position = "top",
    legend.title = element_text(size = rel(0.9)),
    legend.text = element_text(size = rel(0.7)),
    legend.key.width = unit(1, "cm"),
    legend.
    legend.background = element_rect(fill = alpha("white", 0.5))
  )
p
ggsave("../img/20240321-uPBM-E-score-compare.png", width = 4, height = 4.2)

